name: basic_app
description: Basic multi-platform mobile app with authentication

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.0.0
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7  # Add this line
  shared_preferences: ^2.0.15  # Add this line
  provider: ^6.0.0  # Add this line
  connectivity_plus: ^3.0.2  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true